[network]
bind = "0.0.0.0:8443"

[proxy]
secret = "32d7af2b443aefe2494c31a18f7ce03c"

[obfuscation]
tls = true
tls_domain = "www.cloudflare.com"
fallback_addr = "www.cloudflare.com:443"

[performance]
workers = 2
max_connections = 10000
